### ISSUE TITLE
Heading text unreadable over background image

### ISSUE THREAD

**Issue by chrononaut76** [chrononaut76/rails-airbnboo#10]
https://github.com/chrononaut76/rails-airbnboo/blob/41ecf6ec93298e5206a7b84ccec391f2b085f2e4/app/assets/stylesheets/pages/_home.scss#L3
![Screenshot 2024-04-25 at 23-00-02 RailsAirbnboo](https://github.com/chrononaut76/rails-airbnboo/assets/118705172/4296eea1-f4eb-4691-a702-28ccaafa50dc)

**Comment by KarimIssa1** [comment]
Yes! We just pushed what we did before the end of the session but we'll work on it on Saturday!

**Comment by lauradumi** [comment]
Yes I think that a lot of elements  still need adjustment, like the title placement,  the logo, the options in the drop down menu...

We were also looking to maybe improve the background image but didn't want to waste too much time on that yesterday.
